const Data = [
  {
    key: "1",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "2",
    IdBooks: "Duy khanh",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "3",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "4",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "5",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "6",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "7",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "8",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "9",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "10",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "11",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
  {
    key: "12",
    IdBooks: "John Brown",
    bookName: 'harry poter',
    Status: "available",
    Total: 40,
    Date: "15-10-2020",
    Edit: "check",
    Delete: "delete",
    Barcode: "code",
  },
];

export default Data;
